CVMAwards.Web/Controllers/AwardsController.cs
using AutoMapper;
using CVMAwards.Web.Extensions;
using CVMAwards.Web.Models.Common;
using CVMAwards.Web.ViewModels.Awards;
using CVMAwards.Web.ViewModels.Home;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CVMAwards.Web.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class AwardsController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ILogger<AwardsController> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        readonly IMapper _mapper;
        private readonly ISession _session;
        public AwardsController(IMediator mediator,
            ILogger<AwardsController> logger,
            IHttpContextAccessor httpContextAccessor,
            IMapper mapper)
        {
            _mediator = mediator;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _mapper = mapper;
            //_session = _httpContextAccessor.HttpContext.Session;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetAwardsList()
        {

            JsonResult result = new JsonResult(null);

            string draw = Request.Form["draw"][0];

            var parms = new TableParams();

            var formData = Request.Form;


            parms.Length = Convert.ToInt32(formData["length"].ToString());
            parms.Start = Convert.ToInt32(formData["start"].ToString());
            parms.ColIndex = Convert.ToInt32(formData["order[0][column]"].ToString());
            parms.SortDir = formData["order[0][dir]"].ToString();
            parms.Search = formData["search[value]"].ToString();
            //}            

            var queryresult = new AwardHomeViewModel().GetAwardsList(parms, "awards", true);
            //var queryresult = _mediator.SendAsync(query);
            //_session.SetObject("params", parms);

            //parms = _session.GetObject<TableParams>("params");
            result = Json(new
            {
                draw = Convert.ToInt32(draw),
                recordsTotal = queryresult.TotalRecords,
                recordsFiltered = queryresult.RecordCount,
                data = queryresult.AwardsList
            });
            return result;
        }

        public async Task<IActionResult> AddEdit(int id = 0)
        {
            var request = new AwardsViewModel.AwardsViewQuery();
            request.AwardId = id;

            var response = await _mediator.Send(request);
            //return PartialView("_AddEdit", response);
            return View("AddEdit", response);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit(AwardsViewModel viewModel, CancellationToken token)
        {
            var request = new AwardsViewModel.AwardsViewQuery();
            request.AwardId = viewModel.AwardId;

            var response = await _mediator.Send(request);
            viewModel.Categories = response.Categories;
            viewModel.Months = response.Months;

            if (!ModelState.IsValid)
            {
                return View(viewModel);

            }

            var command = new AwardsViewModel.AwardsViewCommand(viewModel);
            var result = await _mediator.Send(command, token);

            if (result.Success)
            {
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "There was an error saving the award");
            ModelState.AddModelError("", result.Errors.First());
            return View(viewModel);
            
        }
    }//end class AwardsController
}//end namespace

CVMAwards.Web/Controllers/UsersController.cs
using CVMAwards.Core.Account;
using CVMAwards.Web.Extensions;
using CVMAwards.Web.Models.LDAP;
using CVMAwards.Web.Models.Users;
using CVMAwards.Web.Services;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CVMAwards.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IMediator _mediator;
        private readonly ILogger<UsersController> _logger;
        private IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        //private readonly IMapper _mapper;
        readonly IAuthAPIService _service;

        public UsersController(IMediator mediator,
            ILogger<UsersController> logger,
            IHttpContextAccessor httpContextAccessor,
            UserManager<ApplicationUser> userManager,
            RoleManager<ApplicationRole> roleManager,
            IAuthAPIService service)
        {
            _mediator = mediator;
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
            _userManager = userManager;
            _roleManager = roleManager;
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var query = new AspNetUserViewModel.AspNetUserViewModelQuery();
            var result = await _mediator.Send(query);
            return View(result);
        }

        public async Task<IActionResult> AddEdit(string id)
        {
            var query = new AspNetUserViewModel.AspNetUserViewModelQuery();

            if (string.IsNullOrEmpty(id))
            {
                query.Type = "Add";
            }
            else
            {
                query.Type = "Edit";
                query.UserId = id;
            }

            var result = await _mediator.Send(query);
            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit(AspNetUserViewModel command, CancellationToken token)
        {
            var aspNetUserViewModel = new AspNetUserViewModel.AspNetUserViewModelCommand(command);

            var errors = await new AspNetUserViewModel().GetErrors(command, _roleManager, _userManager);

            ModelState.Clear();
            if (errors.Count > 0)
            {
                foreach (var error in errors)
                {
                    ModelState.AddModelError("", error);
                }

                return View(command);
            }

            try
            {
                await _mediator.Send(aspNetUserViewModel, token);
                var result = new LDAPResult();
                result.Success = true;
                result.Errors.Add("User has been saved successfully");
                TempData.Put("LdapImportResult", result);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                ModelState.AddModelError("", "There was an error saving the data");
                return View(command);
            }
        }

        public async Task<IActionResult> LdapImport(bool showExistingUsers = false, string userFilter = null, string filteredGroup = "SelectAGroup")
        {
            var query = new LdapUserImportViewModel.LdapUserImportQuery();
            query.ShowExistingUsers = showExistingUsers;
            query.UserFilter = userFilter;
            query.FilteredGroup = filteredGroup;
            var model = await _mediator.Send(query);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LdapImport(LdapUserImportViewModel model)
        {
            if (ModelState.IsValid)
            {
            }

            var query = new LdapUserImportViewModel.LdapUserImportQuery
            {
                ShowExistingUsers = model.ShowExistingUsers,
                UserFilter = model.UserFilter,
                FilteredGroup = model.FilteredGroup
            };

            var r2 = await _mediator.Send(query);

            return View(r2);
        }

        public async Task<IActionResult> LdapImportUser(string Id)
        {
            var query = new LdapUserImportViewModel.LdapUserImportQuery
            {
                ShowExistingUsers = false,
                UserFilter = Id,
                FilteredGroup = "AllUsers"
            };
            var mod = await _mediator.Send(query);

            var query1 = new AspNetUserViewModel.AspNetUserViewModelQuery();
            query1.Type = "Add";

            var result = await _mediator.Send(query1);

            foreach (var user in mod.Users)
            {
                result.User.FirstName = user.FirstName;
                result.User.LastName = user.LastName;
                result.User.Email = user.Email;
                result.User.UserName = user.UserName;
                result.User.IsDomainUser = true;
                result.User.IsActive = true;
            }

            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LdapImportUser(AspNetUserViewModel command, CancellationToken token)
        {
            var result = new LDAPResult();
            var aspNetUserViewModel = new LdapUserImportViewModel.LdapUserImportViewModelCommand(command);
            //try
            //{
            result = await _mediator.Send(aspNetUserViewModel, token);
            if (result.Success)
            {
                result.Errors.Add("User has been imported successfully");
                TempData.Put("LdapImportResult", result);
                return RedirectToAction("LdapImport");
            }
            else
            {
                result.Success = false;
            }

            //TempData.Put("LdapImportResult", result);
            //return RedirectToAction("LdapImport");
            //}
            //catch (Exception ex)
            //{
            //    if (ex.Message.Contains("Role"))
            //    {
            //        result.Success = false;
            //        result.Errors.Add("At least one role must be selected");
            //        TempData.Put("LdapImportResult", result);
            //    }
            //    else //if (ex.Message.Contains("Add") || ex.Message.Contains("Save"))
            //    {
            //        result.Success = false;
            //        result.Errors.Add("There was an error saving the data");
            //        result.Errors.Add(ex.Message);
            //        TempData.Put("LdapImportResult", result);
            //    }
            //    _logger.LogError(ex.Message);
            //}

            var roles = _roleManager.Roles; //_roles.GetAll().ToList();

            foreach (var item in roles)
            {
                foreach (var role in command.RolesList)
                {
                    if (item.Id == role.StringId)
                    {
                        role.Name = item.Name;
                        break;
                    }
                }
            }
            if (!ModelState.IsValid)
            {
                if (ModelState.ContainsKey("Password"))
                {
                    ModelState.Remove("Password");
                }

                if (ModelState.ContainsKey("PasswordConfirm"))
                {
                    ModelState.Remove("PasswordConfirm");
                }

                if (ModelState.ContainsKey("UserRole"))
                {
                    foreach (var role in command.RolesList)
                    {
                        if (role.Checked)
                        {
                            ModelState.Remove("UserRole");
                            break;
                        }
                    }
                }
            }
            return View(command);
        }
    }//end controller
}//end namespace

CVMAwards.Web/Views/Shared/_Footer.cshtml
<style type="text/css">
    /* a {
        color: white;
    }*/
</style>

<div class="row">
    <div class="row">
        <div class="col-sm-6">
            <a href="https://www.msu.edu" title="Click to open Michigan State University Web site" target="_blank">
                <img src="~/images/MSU-Wordmark-White-120-pxls.jpg" alt="Michigan State University Wordmark Screen" height="45" width="180" />
            </a>
        </div>
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-4">
                    <a href="https://cvm.msu.edu/contact" title="Click to open MSU CVM contact page" target="_blank">CVM Contact Information</a>
                </div>
                <div class="col-sm-4">
                    <a href="https://cvm.msu.edu/about/privacy-statement" title="Click to open MSU CVM privacy policy page" target="_blank">Privacy Policy</a>
                </div>
                <div class="col-sm-4">
                    Visit: <a href="https://www.msu.edu" target="_blank" title="Click to open MSU web site">msu.edu</a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4" style="font-size:smaller">
                    Call MSU: (517)355-1855
                </div>
                <div class="col-sm-8" style="font-size:smaller">
                    MSU is an affirmative-action, equal-opportunity <br /> employer
                </div>
            </div>
        </div>
    </div>
    @*<div class="col-sm-2">
            <a href="https://cvm.msu.edu/contact" title="Click to open MSU CVM contact page" target="_blank">CVM Contact Information</a>
        </div>
        <div class="col-sm-2">
            <a href="https://cvm.msu.edu/about/privacy-statement" title="Click to open MSU CVM privacy policy page" target="_blank">Privacy Policy</a>
        </div>
        <div class="col-sm-2">
            Visit: <a href="https://www.msu.edu" target="_blank" title="Click to open MSU web site">msu.edu</a>
        </div>*@
</div>

@*<div class="row">
        <div class="col-sm-6">&nbsp;</div>
        <div class="col-sm-2" style="font-size:smaller">
            Call MSU: (517)355-1855
        </div>
        <div class="col-sm-4" style="font-size:smaller">
            MSU is an affirmative-action, equal-opportunity employer
        </div>
    </div>*@

<div class="row">
    <div class="offset-5 col-sm-7">SPARTANS WILL &copy; @DateTime.Now.Year - MSU-CVM</div>
    @*<div class="col-sm-6" style="font-size:smaller">
            SPARTANS WILL &copy; @DateTime.Now.Year - MSU-CVM
        </div>*@
</div>

CVMAwards.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CVM Awards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CVMAwards.Web.styles.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand me-5" asp-area="" asp-controller="Home" asp-action="Index" title="Click to go to home page">
                    @*<img src="~/images/MSU Veterinary Medical Center Logo2.jpg" alt="CVM logo" />*@
                    <img src="~/Images/CVM-MSU_Wordmark_stacked.png" alt="CVM logo" />
                </a>
                <label class="alert alert-secondary" style="font-size:larger">CVM Awards Portal</label>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Manager")))
                        {
                            <li class="nav-item dropdown">
                                <a class="dropdown-toggle nav-link" href="#" id="adminDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-controller="Awards" asp-action="index" title="Click to go to Awards management page">Manage Awards</a>
                                </div>
                            </li>
                        }

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="dropdown-toggle nav-link" href="#" id="adminDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin
                                </a>
                                <div class="dropdown-menu" aria-labelledby="adminDropdown">
                                    <a class="dropdown-item" asp-controller="Users" asp-action="index" title="Click to go to users List page">Users</a>
                                    <a class="dropdown-item" asp-controller="Roles" asp-action="index" title="Click to go to roles List page">Roles</a>
                                    <a class="dropdown-item" asp-controller="MasterCodes" asp-action="index" title="Click to go Manage Codes">Codes</a>
                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Contact">Contact</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="Account">
                                    <button type="submit" class="nav-link btn btn-link py-0">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Register" class="nav-link" title="Click to register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Login" class="nav-link" title="Click to login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CVMAwards.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CVMAwards.Web/Views/Shared/_Modal.cshtml
@model CVMAwards.Web.Models.Common.BootstrapModal

<style type="text/css">
    #modal-view-app .modal-dialog {
        overflow-y: initial !important;
    }

    #modal-view-app .modal-content {
        height: 500px;
        overflow-y: auto;
        overflow-x: hidden;
    }
</style>

<div aria-hidden="true" aria-labelledby="@Model.AreaLabeledId" role="dialog" tabindex="-1"
     id="@Model.ID" class="modal fade" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content" style="background-color:lightgray;padding:10px;">
        </div>
    </div>
</div>